### ISSUE TITLE
Support ARM Automated Builds

### ISSUE THREAD

**Issue by rdaries** [yunfandev/ghost#2]
Multi-Arch Dockerfile Support (ARM64)

**Comment by yunfandev** [comment]
@rdaries Arm64 support has been added

**Comment by rdaries** [comment]
```
----------------------------------------
IncorrectUsageError: Unable to find storage adapter ghost-storage-cloudinary in ,/var/lib/ghost/content/adapters/,/var/lib/ghost/versions/5.32.0/core/server/adapters/.
    at AdapterManager.getAdapter (/var/lib/ghost/versions/5.32.0/node_modules/@tryghost/adapter-manager/lib/AdapterManager.js:119:19)
    at Object.getAdapter (/var/lib/ghost/versions/5.32.0/core/server/services/adapter-manager/index.js:31:31)
    at Object.getStorage (/var/lib/ghost/versions/5.32.0/core/server/adapters/storage/index.js:14:27)
    at setupSiteApp (/var/lib/ghost/versions/5.32.0/core/frontend/web/site.js:85:71)
    at module.exports (/var/lib/ghost/versions/5.32.0/core/server/web/parent/frontend.js:22:58)
    at initExpressApps (/var/lib/ghost/versions/5.32.0/core/boot.js:230:68)
    at bootGhost (/var/lib/ghost/versions/5.32.0/core/boot.js:461:32)
[2023-01-28 10:41:38] WARN Ghost is shutting down
[2023-01-28 10:41:38] WARN Ghost has shut down
[2023-01-28 10:41:38] WARN Your site is now offline
[2023-01-28 10:41:38] WARN Ghost was running for a few seconds
[2023-01-28 10:41:41] INFO Ghost is running in production...
[2023-01-28 10:41:41] INFO Your site is now available on https://example.com/
[2023-01-28 10:41:41] INFO Ctrl+C to shut down
[2023-01-28 10:41:41] INFO Ghost server started in 0.719s
[2023-01-28 10:41:41] INFO Database is in a ready state.
[2023-01-28 10:41:42] INFO Ghost database ready in 1.086s
[2023-01-28 10:41:44] ERROR Unable to find storage adapter ghost-storage-cloudinary in ,/var/lib/ghost/content/adapters/,/var/lib/ghost/versions/5.32.0/core/server/adapters/.
Unable to find storage adapter ghost-storage-cloudinary in ,/var/lib/ghost/content/adapters/,/var/lib/ghost/versions/5.32.0/core/server/adapters/.
Error ID:
    5baac670-9ef8-11ed-9976-6d63effe3169
```

**Comment by yunfandev** [comment]
> ```
> ----------------------------------------
> IncorrectUsageError: Unable to find storage adapter ghost-storage-cloudinary in ,/var/lib/ghost/content/adapters/,/var/lib/ghost/versions/5.32.0/core/server/adapters/.
>     at AdapterManager.getAdapter (/var/lib/ghost/versions/5.32.0/node_modules/@tryghost/adapter-manager/lib/AdapterManager.js:119:19)
>     at Object.getAdapter (/var/lib/ghost/versions/5.32.0/core/server/services/adapter-manager/index.js:31:31)
>     at Object.getStorage (/var/lib/ghost/versions/5.32.0/core/server/adapters/storage/index.js:14:27)
>     at setupSiteApp (/var/lib/ghost/versions/5.32.0/core/frontend/web/site.js:85:71)
>     at module.exports (/var/lib/ghost/versions/5.32.0/core/server/web/parent/frontend.js:22:58)
>     at initExpressApps (/var/lib/ghost/versions/5.32.0/core/boot.js:230:68)
>     at bootGhost (/var/lib/ghost/versions/5.32.0/core/boot.js:461:32)
> [2023-01-28 10:41:38] WARN Ghost is shutting down
> [2023-01-28 10:41:38] WARN Ghost has shut down
> [2023-01-28 10:41:38] WARN Your site is now offline
> [2023-01-28 10:41:38] WARN Ghost was running for a few seconds
> [2023-01-28 10:41:41] INFO Ghost is running in production...
> [2023-01-28 10:41:41] INFO Your site is now available on https://example.com/
> [2023-01-28 10:41:41] INFO Ctrl+C to shut down
> [2023-01-28 10:41:41] INFO Ghost server started in 0.719s
> [2023-01-28 10:41:41] INFO Database is in a ready state.
> [2023-01-28 10:41:42] INFO Ghost database ready in 1.086s
> [2023-01-28 10:41:44] ERROR Unable to find storage adapter ghost-storage-cloudinary in ,/var/lib/ghost/content/adapters/,/var/lib/ghost/versions/5.32.0/core/server/adapters/.
> Unable to find storage adapter ghost-storage-cloudinary in ,/var/lib/ghost/content/adapters/,/var/lib/ghost/versions/5.32.0/core/server/adapters/.
> Error ID:
>     5baac670-9ef8-11ed-9976-6d63effe3169
> ```

Try to recreate your data volume. `ghost-storage-cloudinary` folder doesn't exists in your current data volume
